# Generated by Django 5.0.6 on 2024-05-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='dataType',
        ),
    ]
